// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARRLyaMwyrhubQVXRjV0DPgabrTtPCZrA',
    appId: '1:193947769448:web:5d9a5af08cee93e64ff9dd',
    messagingSenderId: '193947769448',
    projectId: 'sdu-match-ab7a6',
    authDomain: 'sdu-match-ab7a6.firebaseapp.com',
    storageBucket: 'sdu-match-ab7a6.firebasestorage.app',
    measurementId: 'G-H5WHEG153X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0V6h8473QJNRa3lmJ_xJfExhS44jeoDw',
    appId: '1:193947769448:android:488529fc2cc3861c4ff9dd',
    messagingSenderId: '193947769448',
    projectId: 'sdu-match-ab7a6',
    storageBucket: 'sdu-match-ab7a6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA88sypKNfcEc6NKZEKcAr5QDAOUq_K6yk',
    appId: '1:193947769448:ios:2a661e87d01891904ff9dd',
    messagingSenderId: '193947769448',
    projectId: 'sdu-match-ab7a6',
    storageBucket: 'sdu-match-ab7a6.firebasestorage.app',
    iosBundleId: 'com.example.sduTinder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA88sypKNfcEc6NKZEKcAr5QDAOUq_K6yk',
    appId: '1:193947769448:ios:2a661e87d01891904ff9dd',
    messagingSenderId: '193947769448',
    projectId: 'sdu-match-ab7a6',
    storageBucket: 'sdu-match-ab7a6.firebasestorage.app',
    iosBundleId: 'com.example.sduTinder',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyARRLyaMwyrhubQVXRjV0DPgabrTtPCZrA',
    appId: '1:193947769448:web:f8225f9cd8e11e544ff9dd',
    messagingSenderId: '193947769448',
    projectId: 'sdu-match-ab7a6',
    authDomain: 'sdu-match-ab7a6.firebaseapp.com',
    storageBucket: 'sdu-match-ab7a6.firebasestorage.app',
    measurementId: 'G-C6H0QGKHWP',
  );
}
